"""Event-driven historical backtesting."""

from packages.backtesting.costs import (
    ChargeBreakdown,
    IndiaChargeSchedule,
    IndiaCostModel,
    IndianMarketProduct,
)
from packages.backtesting.engine import (
    BacktestConfig,
    BacktestCostModel,
    BacktestResult,
    BacktestRiskDecision,
    BacktestRiskPolicy,
    BacktestTrade,
    ExitReason,
    FixedFractionRiskPolicy,
    GenericCostModel,
    PerformanceMetrics,
    run_backtest,
)
from packages.backtesting.reporting import (
    DirectionPerformance,
    PerformanceReport,
    PeriodReturn,
    build_performance_report,
)
from packages.backtesting.validation import (
    BenchmarkComparison,
    CandidateValidationScore,
    ChronologicalSplit,
    CostSensitivityPoint,
    MonteCarloResult,
    OutOfSampleResult,
    ParameterStabilityResult,
    WalkForwardFold,
    assess_parameter_stability,
    chronological_split,
    compare_benchmark,
    cost_sensitivity,
    monte_carlo_trade_sequences,
    run_out_of_sample_selection,
    walk_forward_folds,
)

__all__ = [
    "BacktestConfig",
    "BacktestCostModel",
    "BacktestResult",
    "BacktestRiskDecision",
    "BacktestRiskPolicy",
    "BacktestTrade",
    "BenchmarkComparison",
    "CandidateValidationScore",
    "ChargeBreakdown",
    "ChronologicalSplit",
    "CostSensitivityPoint",
    "DirectionPerformance",
    "ExitReason",
    "FixedFractionRiskPolicy",
    "GenericCostModel",
    "IndiaChargeSchedule",
    "IndiaCostModel",
    "IndianMarketProduct",
    "MonteCarloResult",
    "OutOfSampleResult",
    "ParameterStabilityResult",
    "PerformanceMetrics",
    "PerformanceReport",
    "PeriodReturn",
    "WalkForwardFold",
    "assess_parameter_stability",
    "build_performance_report",
    "chronological_split",
    "compare_benchmark",
    "cost_sensitivity",
    "monte_carlo_trade_sequences",
    "run_backtest",
    "run_out_of_sample_selection",
    "walk_forward_folds",
]
