#!/bin/sh
set -eu
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=ON_ERROR_STOP=1 --set=app_password="$MTS_DB_APP_PASSWORD" <<'SQL'
SELECT format('CREATE ROLE mts_app LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION', :'app_password') \gexec
GRANT CONNECT ON DATABASE mts TO mts_app;
GRANT USAGE ON SCHEMA public TO mts_app;
ALTER DEFAULT PRIVILEGES FOR ROLE mts_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mts_app;
ALTER DEFAULT PRIVILEGES FOR ROLE mts_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO mts_app;
SQL
